### ISSUE TITLE
App is hard-coded to use http://localhost:3000

### ISSUE THREAD

**Issue by FarisZR** [Zaki-1052/GPTPortal#12]
~~Hey I'm running this behind a cloudflared tunnel, and I'm getting a 401 unauthorized when sending any message, however trying the service locally on the same server works fine.~~

~~Is there a way to enable a debug mode to see what the issue is?~~

The issue is that the app is just hardcoded to use http://localhost for everything internal.

**Comment by FarisZR** [comment]
i think i know what's the issue here, the app is calling for resources on localhost, and not actually using the domain its running on.

**Comment by Zaki-1052** [comment]
Updated, should be fixed now to be more flexible with the configurations! 

- By default, it still uses `localhost:3000` (with _OR_ statements), but if you set `HOST` and `PORT` in the `.env` file, it will use those for all internal links by sending the specified variables as a config file to the frontend.
- Also set the base URLs for the endpoints, as the script is loaded, following the variable format **http://{HOST}:{PORT}/{endpoint}**, so it isn't hard-coded anymore and can adapt based on the config vars.
- Added a line for running behind a proxy, which should help with your Cloudflare setup.
- Updated input handling scheme to work with both GPT image arrays and text string messages via Mistral.

Should be good now, please test with your setup to make sure and reopen the issue if there's still a problem!
