### ISSUE TITLE
Error sending message. Please try again.

### ISSUE THREAD

**Issue by Inkhomi86** [Zaki-1052/GPTPortal#17]
Latest docker version when typing a message always returns "Error sending message. Please try again." Attaching yaml file and screenshot
[yaml.txt](https://github.com/Zaki-1052/GPTPortal/files/14742957/yaml.txt)
![Screenshot](https://github.com/Zaki-1052/GPTPortal/assets/50901164/de5226ff-6b35-4bd7-ae50-c939899ee926)

**Comment by Zaki-1052** [comment]
@Inkhomi86 Fixed on most recent commit.
