### ISSUE TITLE
The application goes into a redirect loop

### ISSUE THREAD

**Issue by McAvity** [Zaki-1052/GPTPortal#21]
with all default settings, freshly cloned repo, the app goes into redirect loop after logging in.

<img width="1166" alt="Screenshot 2024-04-06 at 22 49 57" src="https://github.com/Zaki-1052/GPTPortal/assets/15800238/287bc620-0b7c-4438-b830-140a42ee1ca6">

Environment:
- macOS: Sonoma 14.3.1 (23D60)
- node version: v20.12.1
- Browser: firefox and safari
- commit: 5bb59c35fab07b91f176a8a7679685aff33919d8

**Comment by Zaki-1052** [comment]
The URL in this case would simply be 
`HOST:PORT/portal`
or for you: 
`0.0.0.0:3000/portal`
**not**:
`0.0.0.0:3000/public/portal.html`
The current URL structure is trying to find a _public_ folder inside the existing one. Please try again with the modified URL.

```
0.0.0.0:3000/portal
```
