### ISSUE TITLE
what am I missing?

### ISSUE THREAD

**Issue by cnseubert** [Zaki-1052/GPTPortal#24]
I must be missing something. 
npm install runs fine
copied .env.example to .env
I configure the .env with my keys and username and password
changed nothing else
start the server.js 
load localhost:3000 in firefox or chrome
http://localhost:3000/portal redirects to http://localhost:3000/public/portal.html

get a redirect loop

running on windows 11,
> node --version
v20.9.0

any suggestions?

Thanks

**Comment by Zaki-1052** [comment]
Should be fixed now. The former URL is correct, the `/public` is unnecessary and was mistakenly added after someone was having trouble accessing through Vercel. 

As long as you are redirected to `http://localhost:3000/portal`, then you're good to go! My local config has been tested too many times in prod; sorry I missed this!

**Comment by cnseubert** [comment]
confirmed fixed! Thank you
