### ISSUE TITLE
GoogleGenerativeAI Error: fetch is not defined

### ISSUE THREAD

**Issue by YasserLamasa** [Zaki-1052/GPTPortal#25]
I set the default model as `gemini-1.5-flash` and I already choose it from the dropdown menu but when I ask send the prompt I get this error message:

Error with Gemini API: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent: fetch is not defined

Here's the web console log:
Error sending message to server: Error: HTTP error! status: 500
    at sendMessageToServer (script.js:2198:19)
    at async HTMLButtonElement.<anonymous> (script.js:1848:15)

Running the app on Windows 11.

**Comment by Zaki-1052** [comment]
**itWorksOnMyMachine**.
<img width="552" alt="Screenshot 2024-08-03 at 3 57 28 PM" src="https://github.com/user-attachments/assets/1ba2aa32-80fe-45d4-b26a-614a5dab0fe5">
In all seriousness, make sure that you've spelled it right in the `.env` file: 

```env
DEFAULT_MODEL=gemini-1.5-flash
```

It will work as well if you put `'gemini-1.5-flash'` as a string.
Also make sure that you've pulled the latest version with `git pull origin main`, in case Google made any recent changes to the API.

---

That being said, it looks like this is probably your issue: https://github.com/google-gemini/generative-ai-js/issues/6

According to [this comment](https://github.com/google-gemini/generative-ai-js/issues/6#issuecomment-1856223452), the Google Gemini SDK requires **Node.js 18+**.

## Solution

As `fetch` is a function used in the Gemini API and was introduced in v18, you should update your Node.js install and try again. Steps are below: 

1. You can check your current Node.js version by running:

```
node --version
```

2. If it's below v18, follow these steps to update:

   - Visit the official Node.js website: https://nodejs.org/
   - Download the LTS (Long Term Support) version, which should be 18.x or higher
   - Run the installer and follow the prompts
   - During installation, make sure to check the box that says "Automatically install the necessary tools"

3. After updating, open a new Command Prompt window and verify the new version:

```
node --version
```

4. Update npm (Node Package Manager) to the latest version:

```
npm install -g npm@latest

```

5. Navigate to your project directory in Command Prompt and reinstall your dependencies:

```
npm install
```

6. Try running it again. The `fetch is not defined` error should now be resolved.

---

7. Alternatively, for easier Node.js version management on Windows, you can use NVM-Windows:

1. Visit the NVM-Windows repository: https://github.com/coreybutler/nvm-windows
2. Download and install the latest version
3. Open a new Command Prompt and install Node.js 18 or higher:

```
nvm install 18
nvm use 18
```

This allows you to easily switch between Node.js versions as needed, and is useful if you were using an older version for specific reason.
If you don't know what I'm talking about, then just install the LTS as described above.

*Hope this helps!*

**Comment by Zaki-1052** [comment]
I pushed a commit to the latest npm packages, so if you `git pull`, there's no need to `npm install` or anything, just make sure your Node.js version is up-to-date. Feel free to reopen the issue if you encounter any more issues.

**Comment by YasserLamasa** [comment]
It was the Node JS version issue. Thanks a lot for your help. It's working now.
